kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: clickhouse-multi-region-federation-demo-muc
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30802
        hostPort: 8802
        protocol: TCP
      - containerPort: 30902
        hostPort: 9802
        protocol: TCP
      - containerPort: 30942
        hostPort: 9842
        protocol: TCP
