kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: clickhouse-multi-region-federation-demo-fra
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30801
        hostPort: 8801
        protocol: TCP
      - containerPort: 30901
        hostPort: 9801
        protocol: TCP
      - containerPort: 30941
        hostPort: 9841
        protocol: TCP
